
//import block start
//////////////////////////////////////////////////////////
import java.util.Scanner;
import java.util.ArrayList;
import java.util.Iterator;
import java.awt.*;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
//////////////////////////////////////////////////////////
//end of import block

public class project3MainGUI extends javax.swing.JFrame {

		//array block
		ArrayList<purchaseInvoice> purchases = new ArrayList<purchaseInvoice>(); 
		ArrayList<salesInvoice> sales = new ArrayList<salesInvoice>(); 
		ArrayList<employee> employees = new ArrayList<employee>();
		ArrayList<customer> customers = new ArrayList<customer>();
		ArrayList<silverCustomer> silverCustomers = new ArrayList<silverCustomer>();
		//end of arrays
		
		//iterator block
		Iterator<employee> emiter = employees.iterator();
		Iterator<customer> citer = customers.iterator();
		Iterator<silverCustomer> sciter = silverCustomers.iterator();
        Iterator<salesInvoice> siiter = sales.iterator();
        Iterator<purchaseInvoice> piter = purchases.iterator();
                
		//end of iterators
        
        static String fileLocation = "inventory.dat";

//Start of form creation
public project3MainGUI() {
		initComponents();
                 
		try {
			FileInputStream fis = new FileInputStream("employeeData.dat");
			ObjectInputStream ois = new ObjectInputStream(fis);
			employees = (ArrayList) ois.readObject();
			ois.close();
			fis.close();
		} 

		catch (IOException ioe){
			ioe.printStackTrace();
			return;
		}			
		
		catch (ClassNotFoundException c){
			System.out.println("Class not found");
			c.printStackTrace();
			return;
		}
		
		try {
			FileInputStream fis = new FileInputStream("customerData.dat");
			ObjectInputStream ois = new ObjectInputStream(fis);
			customers = (ArrayList) ois.readObject();
			ois.close();
			fis.close();
		}
		
		catch (IOException ioe){
			ioe.printStackTrace();
			return;
		}
		
		catch (ClassNotFoundException c){
			System.out.println("Class not found");
			c.printStackTrace();
			return;
		}

		try {
			FileInputStream fis = new FileInputStream("silcustomerData.dat");
			ObjectInputStream ois = new ObjectInputStream(fis);
 
			silverCustomers = (ArrayList) ois.readObject();
 
			ois.close();
			fis.close();
		}
		
		catch (IOException ioe){
			ioe.printStackTrace();
			return;
		}
		
		catch (ClassNotFoundException c){
			System.out.println("Class not found");
			c.printStackTrace();
			return;
		}
		
		try {
			FileInputStream fis = new FileInputStream("purchaseData.dat");
			ObjectInputStream ois = new ObjectInputStream(fis);

			purchases = (ArrayList) ois.readObject();

			ois.close();
			fis.close();
		} 

		catch (IOException ioe){
			ioe.printStackTrace();
			return;
		} 

		catch (ClassNotFoundException c){
			System.out.println("Class not found");
			c.printStackTrace();
			return;
			}

		try {
			FileInputStream fis = new FileInputStream("saleData.dat");
			ObjectInputStream ois = new ObjectInputStream(fis);

			sales = (ArrayList) ois.readObject();

			ois.close();
			fis.close();
		} 

		catch (IOException ioe){
			ioe.printStackTrace();
			return;
		}

		catch (ClassNotFoundException c){
			System.out.println("Class not found");
			c.printStackTrace();
			return;
		}
                
        try
        {
            FileReader r = new FileReader(fileLocation);
            BufferedReader reader = new BufferedReader(r);
            String s = reader.readLine();
            reader.close();
            
            String dataItem[] = s.split(",");
            inventory.addConsole(Integer.parseInt(dataItem[0]));
            inventory.addGames(Integer.parseInt(dataItem[1]));
            inventory.addControllers(Integer.parseInt(dataItem[2]));
            inventory.addAccessories(Integer.parseInt(dataItem[3]));
			inventory.addMemoribilia(Integer.parseInt(dataItem[4]));
            
        }
		
        catch (IOException e)
        {
            JOptionPane.showMessageDialog(this, "File error");
        }
	}

/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frmInv = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlInv = new javax.swing.JTextPane();
        frmCliAdd = new javax.swing.JFrame();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txtCAccID = new javax.swing.JTextField();
        txtCName = new javax.swing.JTextField();
        txtCPhone = new javax.swing.JTextField();
        btnCAdd = new javax.swing.JButton();
        frmCliRem = new javax.swing.JFrame();
        jLabel37 = new javax.swing.JLabel();
        txtRCliID = new javax.swing.JTextField();
        btnRCli = new javax.swing.JButton();
        frmCliMod = new javax.swing.JFrame();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        txtMCAccID = new javax.swing.JTextField();
        txtMCName = new javax.swing.JTextField();
        txtMCPhone = new javax.swing.JTextField();
        btnModC = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        txtMCPoints = new javax.swing.JTextField();
        frmCliView = new javax.swing.JFrame();
        jpnlCliView = new javax.swing.JScrollPane();
        pnlCliView = new javax.swing.JTextArea();
        jpnlSCliView = new javax.swing.JScrollPane();
        pnlSCliView = new javax.swing.JTextArea();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        frmEmpAdd = new javax.swing.JFrame();
        jLabel29 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txtAEmpID = new javax.swing.JTextField();
        txtAEmpName = new javax.swing.JTextField();
        txtAEmpPhone = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txtAEmpWage = new javax.swing.JTextField();
        btnAddEmp = new javax.swing.JButton();
        frmEmpRem = new javax.swing.JFrame();
        jLabel36 = new javax.swing.JLabel();
        txtREmpID = new javax.swing.JTextField();
        btnREmp = new javax.swing.JButton();
        frmEmpMod = new javax.swing.JFrame();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        txtMEmpID = new javax.swing.JTextField();
        txtMEmpName = new javax.swing.JTextField();
        txtMEmpPhone = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        txtMEmpWage = new javax.swing.JTextField();
        btnModEmp = new javax.swing.JButton();
        frmEmpView = new javax.swing.JFrame();
        jpnlEmpView = new javax.swing.JScrollPane();
        pnlEmpView = new javax.swing.JTextArea();
        jLabel49 = new javax.swing.JLabel();
        frmCUp = new javax.swing.JFrame();
        jLabel48 = new javax.swing.JLabel();
        txtCliUp = new javax.swing.JTextField();
        btnUpgrade = new javax.swing.JButton();
        frmPurIn = new javax.swing.JFrame();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtPTran = new javax.swing.JTextField();
        txtPMem = new javax.swing.JTextField();
        txtPAcc = new javax.swing.JTextField();
        txtPCont = new javax.swing.JTextField();
        txtPGames = new javax.swing.JTextField();
        txtPConsole = new javax.swing.JTextField();
        txtPDate = new javax.swing.JTextField();
        txtPAccount = new javax.swing.JTextField();
        btnMakePurch = new javax.swing.JButton();
        txtPTotal = new javax.swing.JTextField();
        txtPPoints = new javax.swing.JTextField();
        btnPurClear = new javax.swing.JButton();
        frmInvoiceView = new javax.swing.JFrame();
        jpnlSInvoice = new javax.swing.JScrollPane();
        pnlSInvoice = new javax.swing.JTextPane();
        jpnlPInvoice = new javax.swing.JScrollPane();
        pnlPInvoice = new javax.swing.JTextPane();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        frmSaleIn = new javax.swing.JFrame();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtSTran = new javax.swing.JTextField();
        txtSMem = new javax.swing.JTextField();
        txtSAcc = new javax.swing.JTextField();
        txtSCont = new javax.swing.JTextField();
        txtSGames = new javax.swing.JTextField();
        txtSConsole = new javax.swing.JTextField();
        txtSDate = new javax.swing.JTextField();
        txtSAccount = new javax.swing.JTextField();
        btnMakeSale = new javax.swing.JButton();
        txtSTotal = new javax.swing.JTextField();
        txtSPoints = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtSEmpID = new javax.swing.JTextField();
        btnSaleClear = new javax.swing.JButton();
        frminvSearch = new javax.swing.JFrame();
        jLabel50 = new javax.swing.JLabel();
        txtinvSearch = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        btnPurch = new javax.swing.JButton();
        btnclientAdd = new javax.swing.JButton();
        btnempMod = new javax.swing.JButton();
        btnInvenView = new javax.swing.JButton();
        btnempView = new javax.swing.JButton();
        btnSale = new javax.swing.JButton();
        btnempAdd = new javax.swing.JButton();
        btnempRem = new javax.swing.JButton();
        btnInvoiceView = new javax.swing.JButton();
        btnclientRemove = new javax.swing.JButton();
        btnclientMod = new javax.swing.JButton();
        btnclientView = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        txtCUp = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        frmInv.setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        frmInv.setSize(new java.awt.Dimension(400, 335));

        pnlInv.setEditable(false);
        jScrollPane1.setViewportView(pnlInv);

        javax.swing.GroupLayout frmInvLayout = new javax.swing.GroupLayout(frmInv.getContentPane());
        frmInv.getContentPane().setLayout(frmInvLayout);
        frmInvLayout.setHorizontalGroup(
            frmInvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmInvLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        frmInvLayout.setVerticalGroup(
            frmInvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmInvLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        frmCliAdd.setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        frmCliAdd.setSize(new java.awt.Dimension(378, 225));

        jLabel30.setText("Customer Account ID:");

        jLabel31.setText("Customer Name:");

        jLabel32.setText("Customer Phone Numer:");

        btnCAdd.setText("Add Customer");
        btnCAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frmCliAddLayout = new javax.swing.GroupLayout(frmCliAdd.getContentPane());
        frmCliAdd.getContentPane().setLayout(frmCliAddLayout);
        frmCliAddLayout.setHorizontalGroup(
            frmCliAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmCliAddLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel30)
                .addGap(90, 90, 90)
                .addComponent(txtCAccID, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(frmCliAddLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel31)
                .addGap(117, 117, 117)
                .addComponent(txtCName, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(frmCliAddLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel32)
                .addGap(78, 78, 78)
                .addComponent(txtCPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(frmCliAddLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(btnCAdd))
        );
        frmCliAddLayout.setVerticalGroup(
            frmCliAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmCliAddLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(frmCliAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(txtCAccID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(frmCliAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(txtCName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(frmCliAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frmCliAddLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel32))
                    .addComponent(txtCPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btnCAdd))
        );

        frmCliRem.setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        frmCliRem.setSize(new java.awt.Dimension(379, 200));

        jLabel37.setText("Customer Account ID to Remove:");

        btnRCli.setText("Remove Customer");
        btnRCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRCliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frmCliRemLayout = new javax.swing.GroupLayout(frmCliRem.getContentPane());
        frmCliRem.getContentPane().setLayout(frmCliRemLayout);
        frmCliRemLayout.setHorizontalGroup(
            frmCliRemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmCliRemLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel37)
                .addGap(12, 12, 12)
                .addComponent(txtRCliID, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(frmCliRemLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(btnRCli))
        );
        frmCliRemLayout.setVerticalGroup(
            frmCliRemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmCliRemLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(frmCliRemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37)
                    .addComponent(txtRCliID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(btnRCli))
        );

        frmCliMod.setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        frmCliMod.setSize(new java.awt.Dimension(387, 275));

        jLabel40.setText("Customer Account ID:");

        jLabel41.setText("Customer Name:");

        jLabel42.setText("Customer Phone Numer:");

        btnModC.setText("Modify Customer");
        btnModC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModCActionPerformed(evt);
            }
        });

        jLabel43.setText("Customer Point Total:");

        javax.swing.GroupLayout frmCliModLayout = new javax.swing.GroupLayout(frmCliMod.getContentPane());
        frmCliMod.getContentPane().setLayout(frmCliModLayout);
        frmCliModLayout.setHorizontalGroup(
            frmCliModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmCliModLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel40)
                .addGap(90, 90, 90)
                .addComponent(txtMCAccID, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(frmCliModLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel41)
                .addGap(117, 117, 117)
                .addComponent(txtMCName, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(frmCliModLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel42)
                .addGap(78, 78, 78)
                .addComponent(txtMCPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(frmCliModLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel43)
                .addGap(53, 53, 53)
                .addComponent(txtMCPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(frmCliModLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(btnModC))
        );
        frmCliModLayout.setVerticalGroup(
            frmCliModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmCliModLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(frmCliModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40)
                    .addComponent(txtMCAccID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(frmCliModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel41)
                    .addComponent(txtMCName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(frmCliModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frmCliModLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel42))
                    .addComponent(txtMCPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(frmCliModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frmCliModLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel43))
                    .addComponent(txtMCPoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btnModC))
        );

        frmCliView.setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        frmCliView.setSize(new java.awt.Dimension(600, 550));

        pnlCliView.setEditable(false);
        pnlCliView.setColumns(20);
        pnlCliView.setRows(5);
        jpnlCliView.setViewportView(pnlCliView);

        pnlSCliView.setEditable(false);
        pnlSCliView.setColumns(20);
        pnlSCliView.setRows(5);
        jpnlSCliView.setViewportView(pnlSCliView);

        jLabel38.setText("Customers:");

        jLabel39.setText("Silver Customers:");

        javax.swing.GroupLayout frmCliViewLayout = new javax.swing.GroupLayout(frmCliView.getContentPane());
        frmCliView.getContentPane().setLayout(frmCliViewLayout);
        frmCliViewLayout.setHorizontalGroup(
            frmCliViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmCliViewLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel38))
            .addGroup(frmCliViewLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jpnlCliView, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(frmCliViewLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel39))
            .addGroup(frmCliViewLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jpnlSCliView, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        frmCliViewLayout.setVerticalGroup(
            frmCliViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmCliViewLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel38)
                .addGap(6, 6, 6)
                .addComponent(jpnlCliView, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel39)
                .addGap(16, 16, 16)
                .addComponent(jpnlSCliView, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        frmEmpAdd.setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        frmEmpAdd.setSize(new java.awt.Dimension(400, 300));

        jLabel29.setText("Employee ID:");

        jLabel33.setText("Employee Name:");

        jLabel34.setText("Employee Phone:");

        jLabel35.setText("Employee Wage:");

        btnAddEmp.setText("Add Employee");
        btnAddEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEmpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frmEmpAddLayout = new javax.swing.GroupLayout(frmEmpAdd.getContentPane());
        frmEmpAdd.getContentPane().setLayout(frmEmpAddLayout);
        frmEmpAddLayout.setHorizontalGroup(
            frmEmpAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmEmpAddLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel29)
                .addGap(74, 74, 74)
                .addComponent(txtAEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(frmEmpAddLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel33)
                .addGap(77, 77, 77)
                .addComponent(txtAEmpName, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(frmEmpAddLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel34)
                .addGap(74, 74, 74)
                .addComponent(txtAEmpPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(frmEmpAddLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel35)
                .addGap(56, 56, 56)
                .addComponent(txtAEmpWage, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(frmEmpAddLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(btnAddEmp))
        );
        frmEmpAddLayout.setVerticalGroup(
            frmEmpAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmEmpAddLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(frmEmpAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(txtAEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(frmEmpAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(txtAEmpName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(frmEmpAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frmEmpAddLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel34))
                    .addComponent(txtAEmpPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(frmEmpAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35)
                    .addComponent(txtAEmpWage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(btnAddEmp))
        );

        frmEmpRem.setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        frmEmpRem.setSize(new java.awt.Dimension(375, 200));

        jLabel36.setText("Employee ID to Remove:");

        btnREmp.setText("Remove Employee");
        btnREmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnREmpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frmEmpRemLayout = new javax.swing.GroupLayout(frmEmpRem.getContentPane());
        frmEmpRem.getContentPane().setLayout(frmEmpRemLayout);
        frmEmpRemLayout.setHorizontalGroup(
            frmEmpRemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmEmpRemLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel36)
                .addGap(46, 46, 46)
                .addComponent(txtREmpID, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(frmEmpRemLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(btnREmp))
        );
        frmEmpRemLayout.setVerticalGroup(
            frmEmpRemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmEmpRemLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(frmEmpRemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36)
                    .addComponent(txtREmpID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnREmp))
        );

        frmEmpMod.setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        frmEmpMod.setSize(new java.awt.Dimension(375, 300));

        jLabel44.setText("Employee ID:");

        jLabel45.setText("Employee Name:");

        jLabel46.setText("Employee Phone:");

        jLabel47.setText("Employee Wage:");

        btnModEmp.setText("Modify Employee");
        btnModEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModEmpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frmEmpModLayout = new javax.swing.GroupLayout(frmEmpMod.getContentPane());
        frmEmpMod.getContentPane().setLayout(frmEmpModLayout);
        frmEmpModLayout.setHorizontalGroup(
            frmEmpModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmEmpModLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel44)
                .addGap(74, 74, 74)
                .addComponent(txtMEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(frmEmpModLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel45)
                .addGap(77, 77, 77)
                .addComponent(txtMEmpName, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(frmEmpModLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel46)
                .addGap(74, 74, 74)
                .addComponent(txtMEmpPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(frmEmpModLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel47)
                .addGap(56, 56, 56)
                .addComponent(txtMEmpWage, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(frmEmpModLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(btnModEmp))
        );
        frmEmpModLayout.setVerticalGroup(
            frmEmpModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmEmpModLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(frmEmpModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel44)
                    .addComponent(txtMEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(frmEmpModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel45)
                    .addComponent(txtMEmpName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(frmEmpModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frmEmpModLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel46))
                    .addComponent(txtMEmpPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(frmEmpModLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel47)
                    .addComponent(txtMEmpWage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(btnModEmp))
        );

        frmEmpView.setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        frmEmpView.setSize(new java.awt.Dimension(475, 400));

        pnlEmpView.setEditable(false);
        pnlEmpView.setColumns(20);
        pnlEmpView.setRows(5);
        jpnlEmpView.setViewportView(pnlEmpView);

        jLabel49.setText("Employees:");

        javax.swing.GroupLayout frmEmpViewLayout = new javax.swing.GroupLayout(frmEmpView.getContentPane());
        frmEmpView.getContentPane().setLayout(frmEmpViewLayout);
        frmEmpViewLayout.setHorizontalGroup(
            frmEmpViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmEmpViewLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel49))
            .addGroup(frmEmpViewLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jpnlEmpView, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        frmEmpViewLayout.setVerticalGroup(
            frmEmpViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmEmpViewLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel49)
                .addGap(16, 16, 16)
                .addComponent(jpnlEmpView, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        frmCUp.setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        frmCUp.setSize(new java.awt.Dimension(375, 200));

        jLabel48.setText("Clustomer Account ID to Upgrade:");

        btnUpgrade.setLabel("Upgrade Customer");
        btnUpgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpgradeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frmCUpLayout = new javax.swing.GroupLayout(frmCUp.getContentPane());
        frmCUp.getContentPane().setLayout(frmCUpLayout);
        frmCUpLayout.setHorizontalGroup(
            frmCUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmCUpLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel48)
                .addGap(10, 10, 10)
                .addComponent(txtCliUp, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(frmCUpLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(btnUpgrade))
        );
        frmCUpLayout.setVerticalGroup(
            frmCUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmCUpLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(frmCUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel48)
                    .addComponent(txtCliUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btnUpgrade))
        );

        frmPurIn.setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        frmPurIn.setSize(new java.awt.Dimension(425, 425));

        jLabel6.setText("Points Earned:");

        jLabel7.setText("Customer's Account Number:");

        jLabel8.setText("Transaction ID:");

        jLabel9.setText("Date:");

        jLabel10.setText("Number of Accessories Purchased:");

        jLabel11.setText("Number of Controllers Purchased:");

        jLabel12.setText("Number of Games Purchased:");

        jLabel13.setText("Number of Consoles Purchased:");

        jLabel14.setText("Number of Memoribilia Purchased:");

        jLabel15.setText("Total:");

        txtPMem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPMemActionPerformed(evt);
            }
        });

        txtPAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPAccountActionPerformed(evt);
            }
        });

        btnMakePurch.setText("Make Purchase");
        btnMakePurch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakePurchActionPerformed(evt);
            }
        });

        txtPTotal.setEditable(false);

        txtPPoints.setEditable(false);

        btnPurClear.setText("Clear");
        btnPurClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPurClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frmPurInLayout = new javax.swing.GroupLayout(frmPurIn.getContentPane());
        frmPurIn.getContentPane().setLayout(frmPurInLayout);
        frmPurInLayout.setHorizontalGroup(
            frmPurInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmPurInLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel7)
                .addGap(94, 94, 94)
                .addComponent(txtPAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(frmPurInLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel8)
                .addGap(165, 165, 165)
                .addComponent(txtPTran, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(frmPurInLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel9)
                .addGap(213, 213, 213)
                .addComponent(txtPDate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(frmPurInLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel13)
                .addGap(83, 83, 83)
                .addComponent(txtPConsole, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(frmPurInLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel12)
                .addGap(94, 94, 94)
                .addComponent(txtPGames, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(frmPurInLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel11)
                .addGap(84, 84, 84)
                .addComponent(txtPCont, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(frmPurInLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel10)
                .addGap(81, 81, 81)
                .addComponent(txtPAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(frmPurInLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel14)
                .addGap(94, 94, 94)
                .addComponent(txtPMem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(frmPurInLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnMakePurch)
                .addGap(115, 115, 115)
                .addComponent(btnPurClear))
            .addGroup(frmPurInLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel15)
                .addGap(172, 172, 172)
                .addComponent(txtPTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(frmPurInLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel6)
                .addGap(169, 169, 169)
                .addComponent(txtPPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        frmPurInLayout.setVerticalGroup(
            frmPurInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmPurInLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(frmPurInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frmPurInLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7))
                    .addComponent(txtPAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(frmPurInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frmPurInLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8))
                    .addComponent(txtPTran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(frmPurInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frmPurInLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel9))
                    .addComponent(txtPDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(frmPurInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(txtPConsole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(frmPurInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(txtPGames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(frmPurInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frmPurInLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel11))
                    .addComponent(txtPCont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(frmPurInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frmPurInLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel10))
                    .addComponent(txtPAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(frmPurInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frmPurInLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel14))
                    .addComponent(txtPMem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(frmPurInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMakePurch)
                    .addComponent(btnPurClear))
                .addGap(27, 27, 27)
                .addGroup(frmPurInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(txtPTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(frmPurInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtPPoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        frmInvoiceView.setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        frmInvoiceView.setSize(new java.awt.Dimension(675, 575));

        pnlSInvoice.setEditable(false);
        jpnlSInvoice.setViewportView(pnlSInvoice);

        pnlPInvoice.setEditable(false);
        jpnlPInvoice.setViewportView(pnlPInvoice);

        jLabel16.setText("Purchases:");

        jLabel17.setText("Sales:");

        javax.swing.GroupLayout frmInvoiceViewLayout = new javax.swing.GroupLayout(frmInvoiceView.getContentPane());
        frmInvoiceView.getContentPane().setLayout(frmInvoiceViewLayout);
        frmInvoiceViewLayout.setHorizontalGroup(
            frmInvoiceViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmInvoiceViewLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel16)
                .addGap(246, 246, 246)
                .addComponent(jLabel17))
            .addGroup(frmInvoiceViewLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jpnlPInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jpnlSInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        frmInvoiceViewLayout.setVerticalGroup(
            frmInvoiceViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmInvoiceViewLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(frmInvoiceViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addGap(16, 16, 16)
                .addGroup(frmInvoiceViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnlPInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpnlSInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        frmSaleIn.setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        frmSaleIn.setSize(new java.awt.Dimension(450, 500));

        jLabel18.setText("Points Earned:");

        jLabel19.setText("Customer's Account Number:");

        jLabel20.setText("Transaction ID:");

        jLabel21.setText("Date:");

        jLabel22.setText("Number of Accessories Sold:");

        jLabel23.setText("Number of Controllers Sold:");

        jLabel24.setText("Number of Games Sold:");

        jLabel25.setText("Number of Consoles Sold:");

        jLabel26.setText("Number of Memoribilia Sold:");

        jLabel27.setText("Total:");

        txtSMem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSMemActionPerformed(evt);
            }
        });

        txtSAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSAccountActionPerformed(evt);
            }
        });

        btnMakeSale.setText("Make Sale");
        btnMakeSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakeSaleActionPerformed(evt);
            }
        });

        txtSTotal.setEditable(false);

        txtSPoints.setEditable(false);

        jLabel28.setText("Employee ID:");

        btnSaleClear.setText("Clear");
        btnSaleClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaleClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frmSaleInLayout = new javax.swing.GroupLayout(frmSaleIn.getContentPane());
        frmSaleIn.getContentPane().setLayout(frmSaleInLayout);
        frmSaleInLayout.setHorizontalGroup(
            frmSaleInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmSaleInLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel19)
                .addGap(94, 94, 94)
                .addComponent(txtSAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(frmSaleInLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel28)
                .addGap(164, 164, 164)
                .addComponent(txtSEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(frmSaleInLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel20)
                .addGap(165, 165, 165)
                .addComponent(txtSTran, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(frmSaleInLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel21)
                .addGap(213, 213, 213)
                .addComponent(txtSDate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(frmSaleInLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel25)
                .addGap(114, 114, 114)
                .addComponent(txtSConsole, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(frmSaleInLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel24)
                .addGap(124, 124, 124)
                .addComponent(txtSGames, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(frmSaleInLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel23)
                .addGap(115, 115, 115)
                .addComponent(txtSCont, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(frmSaleInLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel22)
                .addGap(112, 112, 112)
                .addComponent(txtSAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(frmSaleInLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel26)
                .addGap(125, 125, 125)
                .addComponent(txtSMem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(frmSaleInLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(btnMakeSale)
                .addGap(121, 121, 121)
                .addComponent(btnSaleClear))
            .addGroup(frmSaleInLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel27)
                .addGap(172, 172, 172)
                .addComponent(txtSTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(frmSaleInLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel18)
                .addGap(169, 169, 169)
                .addComponent(txtSPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        frmSaleInLayout.setVerticalGroup(
            frmSaleInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frmSaleInLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(frmSaleInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frmSaleInLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel19))
                    .addComponent(txtSAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(frmSaleInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(txtSEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(frmSaleInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frmSaleInLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel20))
                    .addComponent(txtSTran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(frmSaleInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frmSaleInLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel21))
                    .addComponent(txtSDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(frmSaleInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(txtSConsole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(frmSaleInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(txtSGames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(frmSaleInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frmSaleInLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel23))
                    .addComponent(txtSCont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(frmSaleInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frmSaleInLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel22))
                    .addComponent(txtSAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(frmSaleInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frmSaleInLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel26))
                    .addComponent(txtSMem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(frmSaleInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMakeSale)
                    .addComponent(btnSaleClear))
                .addGap(27, 27, 27)
                .addGroup(frmSaleInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(txtSTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(frmSaleInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(txtSPoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        frminvSearch.setSize(new java.awt.Dimension(375, 200));

        jLabel50.setText("Invoice ID:");

        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frminvSearchLayout = new javax.swing.GroupLayout(frminvSearch.getContentPane());
        frminvSearch.getContentPane().setLayout(frminvSearchLayout);
        frminvSearchLayout.setHorizontalGroup(
            frminvSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frminvSearchLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel50)
                .addGap(16, 16, 16)
                .addComponent(txtinvSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(frminvSearchLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jButton2))
        );
        frminvSearchLayout.setVerticalGroup(
            frminvSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frminvSearchLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(frminvSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel50)
                    .addComponent(txtinvSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jButton2))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setText("Eastern New Mexico Retro Paradise Point of Sale System");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 10, 500, 90);

        jLabel2.setText("  Customer  ");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 200, 70, 14);

        jLabel3.setText("  Employee  ");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(200, 200, 70, 14);

        jLabel4.setText("  Invoice  ");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(370, 200, 60, 14);

        jLabel5.setText("  Inventory  ");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(540, 200, 70, 14);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(480, 210, 50, 260);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(140, 210, 50, 260);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(310, 210, 50, 260);

        btnPurch.setText("Purchase");
        btnPurch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPurchActionPerformed(evt);
            }
        });
        getContentPane().add(btnPurch);
        btnPurch.setBounds(360, 290, 77, 23);

        btnclientAdd.setText("Add");
        btnclientAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclientAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnclientAdd);
        btnclientAdd.setBounds(40, 250, 51, 23);

        btnempMod.setText("Modify");
        btnempMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnempModActionPerformed(evt);
            }
        });
        getContentPane().add(btnempMod);
        btnempMod.setBounds(200, 340, 80, 23);

        btnInvenView.setText("View");
        btnInvenView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvenViewActionPerformed(evt);
            }
        });
        getContentPane().add(btnInvenView);
        btnInvenView.setBounds(550, 310, 55, 23);

        btnempView.setText("View");
        btnempView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnempViewActionPerformed(evt);
            }
        });
        getContentPane().add(btnempView);
        btnempView.setBounds(210, 380, 55, 23);

        btnSale.setText("Sale");
        btnSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaleActionPerformed(evt);
            }
        });
        getContentPane().add(btnSale);
        btnSale.setBounds(370, 250, 70, 23);

        btnempAdd.setText("Add");
        btnempAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnempAddActionPerformed(evt);
            }
        });
        getContentPane().add(btnempAdd);
        btnempAdd.setBounds(210, 250, 51, 23);

        btnempRem.setText("Remove");
        btnempRem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnempRemActionPerformed(evt);
            }
        });
        getContentPane().add(btnempRem);
        btnempRem.setBounds(200, 300, 73, 23);

        btnInvoiceView.setText("View");
        btnInvoiceView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvoiceViewActionPerformed(evt);
            }
        });
        getContentPane().add(btnInvoiceView);
        btnInvoiceView.setBounds(370, 330, 55, 23);

        btnclientRemove.setText("Remove");
        btnclientRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclientRemoveActionPerformed(evt);
            }
        });
        getContentPane().add(btnclientRemove);
        btnclientRemove.setBounds(30, 300, 73, 23);

        btnclientMod.setText("Modify");
        btnclientMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclientModActionPerformed(evt);
            }
        });
        getContentPane().add(btnclientMod);
        btnclientMod.setBounds(30, 340, 80, 23);

        btnclientView.setText("View");
        btnclientView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclientViewActionPerformed(evt);
            }
        });
        getContentPane().add(btnclientView);
        btnclientView.setBounds(40, 420, 55, 23);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(120, 212, 540, 0);
        getContentPane().add(jSeparator5);
        jSeparator5.setBounds(0, 210, 660, 10);

        txtCUp.setText("Upgrade");
        txtCUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCUpActionPerformed(evt);
            }
        });
        getContentPane().add(txtCUp);
        txtCUp.setBounds(30, 380, 75, 23);

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(370, 380, 67, 23);

        setBounds(0, 0, 677, 507);
    }// </editor-fold>//GEN-END:initComponents

	private void btnPurchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPurchActionPerformed
		frmPurIn.setVisible(true);
	}//GEN-LAST:event_btnPurchActionPerformed

	private void btnclientAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclientAddActionPerformed
		frmCliAdd.setVisible(true);
	}//GEN-LAST:event_btnclientAddActionPerformed

	private void btnempModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnempModActionPerformed
		frmEmpMod.setVisible(true);
	}//GEN-LAST:event_btnempModActionPerformed

	private void btnInvenViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvenViewActionPerformed
		frmInv.setVisible(true);
		pnlInv.setText(inventory.invString());
	}//GEN-LAST:event_btnInvenViewActionPerformed

	private void btnempViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnempViewActionPerformed
		frmEmpView.setVisible(true);
		pnlEmpView.setText(employees.toString().substring(1, employees.toString().length() - 1).replace(", ", ""));
	}//GEN-LAST:event_btnempViewActionPerformed

	private void btnSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaleActionPerformed
		frmSaleIn.setVisible(true);
	}//GEN-LAST:event_btnSaleActionPerformed

	private void btnempAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnempAddActionPerformed
		frmEmpAdd.setVisible(true);
	}//GEN-LAST:event_btnempAddActionPerformed

	private void btnempRemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnempRemActionPerformed
		frmEmpRem.setVisible(true);
	}//GEN-LAST:event_btnempRemActionPerformed

	private void btnInvoiceViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvoiceViewActionPerformed
		frmInvoiceView.setVisible(true);
		pnlPInvoice.setText(purchases.toString().substring(1, purchases.toString().length() - 1).replace(", ", ""));
		pnlSInvoice.setText(sales.toString().substring(1, sales.toString().length() - 1).replace(", ", ""));
	}//GEN-LAST:event_btnInvoiceViewActionPerformed

	private void btnclientRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclientRemoveActionPerformed
		frmCliRem.setVisible(true);
	}//GEN-LAST:event_btnclientRemoveActionPerformed

	private void btnclientModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclientModActionPerformed
		frmCliMod.setVisible(true);
	}//GEN-LAST:event_btnclientModActionPerformed

	private void btnclientViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclientViewActionPerformed
		frmCliView.setVisible(true);
		pnlCliView.setText(customers.toString().substring(1, customers.toString().length() - 1).replace(", ", ""));
		pnlSCliView.setText(silverCustomers.toString().substring(1, silverCustomers.toString().length() - 1).replace(", ", ""));
	}//GEN-LAST:event_btnclientViewActionPerformed

	private void txtPMemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPMemActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_txtPMemActionPerformed

	private void txtPAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPAccountActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_txtPAccountActionPerformed

	private void btnMakePurchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakePurchActionPerformed
		int addpaccountID = Integer.parseInt(txtPAccount.getText());
		int pinvoiceID = Integer.parseInt(txtPTran.getText());
		String pdate = txtPDate.getText();
		int consolePurchased = Integer.parseInt(txtPConsole.getText());
		int gamesPurchased = Integer.parseInt(txtPGames.getText());
		int controllersPurchased = Integer.parseInt(txtPCont.getText());
		int accessoriesPurchased = Integer.parseInt(txtPAcc.getText());
		int memoribiliaPurchased = Integer.parseInt(txtPMem.getText());

		double pamount = (consolePurchased * 100) + 
						(gamesPurchased * 50) + 
						(controllersPurchased * 20) + 
						(accessoriesPurchased * 10) + 
						(memoribiliaPurchased * 5);
							
					
		double ppointsEarned = pamount * .1;
		System.out.println("Points earned: " + ppointsEarned);

		txtPTotal.setText(String.format("%.2f", pamount));
		txtPPoints.setText(String.format("%.2f", ppointsEarned));
					
		for (Iterator<customer> iterator = customers.iterator(); iterator.hasNext();) { //add points to customer account
			customer addpcust = iterator.next();
			if (addpcust.accountID == addpaccountID) {
				addpcust.points = addpcust.points + ppointsEarned;
			}
		}

		for (Iterator<silverCustomer> iterator = silverCustomers.iterator(); iterator.hasNext();) { //add points to customer account
			customer addpscust = iterator.next();
			if (addpscust.accountID == addpaccountID) {
				addpscust.points = addpscust.points + ppointsEarned;
			}
		}

		//start of inventory block
		inventory.addConsole(consolePurchased); 
		inventory.addGames(gamesPurchased);
		inventory.addControllers(controllersPurchased);
		inventory.addAccessories(accessoriesPurchased);
		inventory.addMemoribilia(memoribiliaPurchased);
		//end of inventory block
				
		//start of invoice
		purchases.add(new purchaseInvoice (
							addpaccountID,
							pinvoiceID, 
							pdate, 
							consolePurchased, 
							gamesPurchased, 
							controllersPurchased, 
							accessoriesPurchased, 
							memoribiliaPurchased, 
							pamount, 
							ppointsEarned)); //invoice creation

		try {
			FileOutputStream fos = new FileOutputStream("purchaseData.dat");
			ObjectOutputStream oos = new ObjectOutputStream(fos);
			oos.writeObject(purchases);
			oos.close();
			fos.close();
		} 

		catch (IOException ioe){
			ioe.printStackTrace();
		}

		try {
			FileOutputStream fos = new FileOutputStream("customerData.dat");
			ObjectOutputStream oos = new ObjectOutputStream(fos);
			oos.writeObject(customers);
			oos.close();
			fos.close();
		} 
		
		catch (IOException ioe){
			ioe.printStackTrace();
		}
 
		try {
			FileOutputStream fos = new FileOutputStream("silcustomerData.dat");
			ObjectOutputStream oos = new ObjectOutputStream(fos);
			oos.writeObject(silverCustomers);
			oos.close();
			fos.close();
		} 

		catch (IOException ioe){
			ioe.printStackTrace();
		}
   
		try {
			FileOutputStream fos = new FileOutputStream("employeeData.dat");
			ObjectOutputStream oos = new ObjectOutputStream(fos);
			oos.writeObject(employees);
			oos.close();
			fos.close();
		} 

		catch (IOException ioe){
			ioe.printStackTrace();
		}

		try
        {
            String s = inventory.getConsole() + ",";
            s += inventory.getGames() + ",";
            s += inventory.getControllers() + ",";
            s += inventory.getAccesories() + ",";
			s += inventory.getMemoribilia();
            
            FileWriter w = new FileWriter(fileLocation);
            BufferedWriter writer = new BufferedWriter(w);
            writer.write(s);
            writer.close();
        }
		
        catch (IOException e)
        {
            JOptionPane.showMessageDialog(this, "File error");
        }
		
		JOptionPane.showMessageDialog(this, "Purchase Complete.");		

	}//GEN-LAST:event_btnMakePurchActionPerformed

	private void txtSMemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSMemActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_txtSMemActionPerformed

	private void txtSAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSAccountActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_txtSAccountActionPerformed

	private void btnMakeSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakeSaleActionPerformed
		int addsaccountID = Integer.parseInt(txtSAccount.getText());
		int addsempID = Integer.parseInt(txtSEmpID.getText());
		int sinvoiceID = Integer.parseInt(txtSTran.getText());
		String sdate = txtSDate.getText();
		int consoleSold = Integer.parseInt(txtSConsole.getText());
		int gamesSold = Integer.parseInt(txtSGames.getText());
		int controllersSold = Integer.parseInt(txtSCont.getText());
		int accessoriesSold = Integer.parseInt(txtSAcc.getText());
		int memoribiliaSold = Integer.parseInt(txtSMem.getText());

		double sAmount = (consoleSold * 100) + 
							(gamesSold * 50) + 
							(controllersSold * 20) + 
							(accessoriesSold* 10) + 
							(memoribiliaSold* 5);
	
		double spointsEarned = sAmount * .1;
		System.out.println("Points earned: " + spointsEarned);

		txtSTotal.setText(String.format("%.2f", sAmount));
		txtSPoints.setText(String.format("%.2f", spointsEarned));
					
		for (Iterator<customer> iterator = customers.iterator(); iterator.hasNext();) { //add points to customer account
			customer addscust = iterator.next();
			if (addscust.accountID == addsaccountID) {
				addscust.points = addscust.points + spointsEarned;
			}
		}

		for (Iterator<silverCustomer> iterator = silverCustomers.iterator(); iterator.hasNext();) { //add points to customer account
			customer addsscust = iterator.next();
			if (addsscust.accountID == addsaccountID) {
				addsscust.points = addsscust.points + spointsEarned;
			}
		}

		for (Iterator<employee> iterator = employees.iterator(); iterator.hasNext();) { //add amount to employee's sales total
			employee addsemp = iterator.next();
			if (addsemp.employeeID == addsempID) {
				addsemp.weeklySales = addsemp.weeklySales + sAmount;
			}
		}

		//start of inventory
		inventory.removeConsole(consoleSold);
		inventory.removeGames(gamesSold);
		inventory.removeControllers(controllersSold);
		inventory.removeAccessories(accessoriesSold);
		inventory.removeMemoribilia(memoribiliaSold);
		//end of inventory 
				
		//start of invoice
		sales.add(new salesInvoice (addsempID,
									addsaccountID,
									sinvoiceID, 
									sdate, 
									consoleSold, 
									gamesSold, 
									controllersSold, 
									accessoriesSold, 
									memoribiliaSold, 
									sAmount, 
									spointsEarned)); //invoice creation

		try {
			FileOutputStream fos = new FileOutputStream("saleData.dat");
			ObjectOutputStream oos = new ObjectOutputStream(fos);
			oos.writeObject(sales);
			oos.close();
			fos.close();
		} 

		catch (IOException ioe) {
			ioe.printStackTrace();
		}

		try {
			FileOutputStream fos = new FileOutputStream("customerData.dat");
			ObjectOutputStream oos = new ObjectOutputStream(fos);
			oos.writeObject(customers);
			oos.close();
			fos.close();
		} 
		
		catch (IOException ioe){
			ioe.printStackTrace();
		}

		try {
			FileOutputStream fos = new FileOutputStream("silcustomerData.dat");
			ObjectOutputStream oos = new ObjectOutputStream(fos);
			oos.writeObject(silverCustomers);
			oos.close();
			fos.close();
		} 

		catch (IOException ioe){
			ioe.printStackTrace();
		}

		try {
			FileOutputStream fos = new FileOutputStream("employeeData.dat");
			ObjectOutputStream oos = new ObjectOutputStream(fos);
			oos.writeObject(employees);
			oos.close();
			fos.close();
		} 

		catch (IOException ioe){
			ioe.printStackTrace();
		}

        try
        {
            String s = inventory.getConsole() + ",";
            s += inventory.getGames() + ",";
            s += inventory.getControllers() + ",";
            s += inventory.getAccesories() + ",";
			s += inventory.getMemoribilia();
            
            FileWriter w = new FileWriter(fileLocation);
            BufferedWriter writer = new BufferedWriter(w);
            writer.write(s);
            writer.close();
        }
		
        catch (IOException e)
        {
            JOptionPane.showMessageDialog(this, "File error");
        }
	
		JOptionPane.showMessageDialog(this, "Sale Complete.");
     
	}//GEN-LAST:event_btnMakeSaleActionPerformed

	private void btnCAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCAddActionPerformed
		int accountID = Integer.parseInt(txtCAccID.getText());
		String cname = txtCName.getText();
		String cphoneNumber = txtCPhone.getText();
		customers.add(new customer (accountID, cname, cphoneNumber, 0));

		try {
			FileOutputStream fos = new FileOutputStream("customerData.dat");
			ObjectOutputStream oos = new ObjectOutputStream(fos);
			oos.writeObject(customers);
			oos.close();
			fos.close();
		} 

		catch (IOException ioe){
			ioe.printStackTrace();
		}
		
		JOptionPane.showMessageDialog(this, "Client Added.");
		txtCAccID.setText("");
		txtCName.setText("");
		txtCPhone.setText("");
	}//GEN-LAST:event_btnCAddActionPerformed

	private void btnAddEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEmpActionPerformed
		int aEmployeeID = Integer.parseInt(txtAEmpID.getText());
		String aEname = txtAEmpName.getText();
		String aEphonenumber = txtAEmpPhone.getText();
		int aEwage = Integer.parseInt(txtAEmpWage.getText());
		employees.add(new employee (aEmployeeID, aEname, aEphonenumber, aEwage, 0));
		
		try {
			FileOutputStream fos = new FileOutputStream("employeeData.dat");
			ObjectOutputStream oos = new ObjectOutputStream(fos);
			oos.writeObject(employees);
			oos.close();
			fos.close();
		} 

		catch (IOException ioe) {
			ioe.printStackTrace();
		}

		JOptionPane.showMessageDialog(this, "Employee Added.");
		txtAEmpID.setText("");
		txtAEmpName.setText("");
		txtAEmpPhone.setText("");
		txtAEmpWage.setText("");
	}//GEN-LAST:event_btnAddEmpActionPerformed

	private void btnREmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnREmpActionPerformed
		int remployeeID = Integer.parseInt(txtREmpID.getText());
		boolean rEmpFound = false;
		for (Iterator<employee> iterator = employees.iterator(); iterator.hasNext();) {
			if (iterator.next().employeeID == remployeeID){
				iterator.remove();
				JOptionPane.showMessageDialog(this, "Employee Removed.");
				rEmpFound = true;
			}
		}

		if (rEmpFound == false){
			JOptionPane.showMessageDialog(this, "Employee Not Found.");
		}

		try {
			FileOutputStream fos = new FileOutputStream("employeeData.dat");
			ObjectOutputStream oos = new ObjectOutputStream(fos);
			oos.writeObject(employees);
			oos.close();
			fos.close();
		} 

		catch (IOException ioe){
			ioe.printStackTrace();
		}

		txtREmpID.setText("");
	}//GEN-LAST:event_btnREmpActionPerformed

	private void btnRCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRCliActionPerformed
		int raccountID = Integer.parseInt(txtRCliID.getText());
		boolean rCusFound = false;
		for (Iterator<customer> iterator = customers.iterator(); iterator.hasNext();) {
			if (iterator.next().accountID == raccountID) {
				iterator.remove();
				JOptionPane.showMessageDialog(this, "Customer Removed.");
				rCusFound = true;
			}
		}   

		for (Iterator<silverCustomer> iterator = silverCustomers.iterator(); iterator.hasNext();) {
			if (iterator.next().accountID == raccountID) {
				iterator.remove();
				JOptionPane.showMessageDialog(this, "Customer Removed.");
				rCusFound = true;
			}
		}

		if (rCusFound = false){
			JOptionPane.showMessageDialog(this, "Customer Not Found.");
		}
		
		try {
			FileOutputStream fos = new FileOutputStream("customerData.dat");
			ObjectOutputStream oos = new ObjectOutputStream(fos);
			oos.writeObject(customers);
			oos.close();
			fos.close();
		} 

		catch (IOException ioe){
			ioe.printStackTrace();
		}

		try {
			FileOutputStream fos = new FileOutputStream("silcustomerData.dat");
			ObjectOutputStream oos = new ObjectOutputStream(fos);
			oos.writeObject(silverCustomers);
			oos.close();
			fos.close();
		} 

		catch (IOException ioe){
			ioe.printStackTrace();
		}
 
		txtRCliID.setText("");
	}//GEN-LAST:event_btnRCliActionPerformed

	private void btnModCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModCActionPerformed
		int maccountID = Integer.parseInt(txtMCAccID.getText());
		String mcname = txtMCName.getText();
		String mcphoneNumber = txtMCPhone.getText();
		double mcpoints = Double.parseDouble(txtMCPoints.getText());
		boolean mCusFound = false;

		for (Iterator<customer> iterator = customers.iterator(); iterator.hasNext();){ //start of the iterator
			customer mcust = iterator.next();
			if (mcust.accountID == maccountID){
				int i = customers.indexOf(mcust);
				customers.set(i, new customer(maccountID, mcname, mcphoneNumber, mcpoints));
				JOptionPane.showMessageDialog(this, "Customer Modified.");
				mCusFound = true;
			} //end of iterator
		}  

		for (Iterator<silverCustomer> iterator = silverCustomers.iterator(); iterator.hasNext();){ //start of the iterator
			silverCustomer mscust = iterator.next();
			if (mscust.accountID == maccountID){
				int i = silverCustomers.indexOf(mscust);
				silverCustomers.set(i, new silverCustomer(maccountID, mcname, mcphoneNumber, mcpoints, mscust.coupon));
				JOptionPane.showMessageDialog(this, "Customer Modified.");
				mCusFound = true;
			} //end of iterator
		}
		
		if (mCusFound = false){
			JOptionPane.showMessageDialog(this, "Customer Not Found.");
		}

		try {
			FileOutputStream fos = new FileOutputStream("customerData.dat");
			ObjectOutputStream oos = new ObjectOutputStream(fos);
			oos.writeObject(customers);
			oos.close();
			fos.close();
		} 

		catch (IOException ioe){
			ioe.printStackTrace();
		}

		try {
			FileOutputStream fos = new FileOutputStream("silcustomerData.dat");
			ObjectOutputStream oos = new ObjectOutputStream(fos);
			oos.writeObject(silverCustomers);
			oos.close();
			fos.close();
		} 

		catch (IOException ioe){
			ioe.printStackTrace();
		}

		txtMCAccID.setText("");
		txtMCName.setText("");
		txtMCPhone.setText("");
		txtMCPoints.setText("");
	}//GEN-LAST:event_btnModCActionPerformed

	private void btnModEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModEmpActionPerformed
		int mEmployeeID = Integer.parseInt(txtMEmpID.getText());
		String mEname = txtMEmpName.getText();
		String mEphonenumber = txtMEmpPhone.getText();
		int mEwage = Integer.parseInt(txtMEmpWage.getText());
		boolean mEmpFound = false;
					
		for (Iterator<employee> iterator = employees.iterator(); iterator.hasNext();) {
			employee memp = iterator.next();
			if (memp.employeeID == mEmployeeID){ 
				double wksales = memp.weeklySales;
				int i = employees.indexOf(memp);
				employees.set(i, new employee(mEmployeeID, mEname, mEphonenumber, mEwage, wksales));
				JOptionPane.showMessageDialog(this, "Employee Modified.");
				mEmpFound = true;
			}
		}

		if (mEmpFound == false){
			JOptionPane.showMessageDialog(this, "Employee Not Found.");
		}

		try {
			FileOutputStream fos = new FileOutputStream("employeeData.dat");
			ObjectOutputStream oos = new ObjectOutputStream(fos);
			oos.writeObject(employees);
			oos.close();
			fos.close();
		}

		catch (IOException ioe){
			ioe.printStackTrace();
		}
		
		txtMEmpID.setText("");
		txtMEmpName.setText("");
		txtMEmpPhone.setText("");
		txtMEmpWage.setText("");
	}//GEN-LAST:event_btnModEmpActionPerformed

	private void txtCUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCUpActionPerformed
		frmCUp.setVisible(true);
	}//GEN-LAST:event_txtCUpActionPerformed

	private void btnUpgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpgradeActionPerformed
		int uacc = Integer.parseInt(txtCliUp.getText());
		boolean uCustFound = false;
		for (Iterator<customer> iterator = customers.iterator(); iterator.hasNext();) { //start of the iterator
			customer ucust = iterator.next();
			if (ucust.accountID == uacc) {
				silverCustomers.add(new silverCustomer (ucust.accountID, ucust.name, ucust.phoneNumber, ucust.points, true));
				JOptionPane.showMessageDialog(this, "Customer Upgraded.");
				uCustFound = true;
			}
		}
							
		for (Iterator<customer> iterator = customers.iterator(); iterator.hasNext();) {
			if (iterator.next().accountID == uacc){ 
				iterator.remove();
			}
		}

		if (uCustFound == false){
			JOptionPane.showMessageDialog(this, "Customer Not Found.");
		}

		try {
			FileOutputStream fos = new FileOutputStream("customerData.dat");
			ObjectOutputStream oos = new ObjectOutputStream(fos);
			oos.writeObject(customers);
			oos.close();
			fos.close();
		} 

		catch (IOException ioe){
			ioe.printStackTrace();
		}

		try {
			FileOutputStream fos = new FileOutputStream("silcustomerData.dat");
			ObjectOutputStream oos = new ObjectOutputStream(fos);
			oos.writeObject(silverCustomers);
			oos.close();
			fos.close();
		} 

		catch (IOException ioe){
			ioe.printStackTrace();
		}

		txtCliUp.setText("");
	}//GEN-LAST:event_btnUpgradeActionPerformed

	private void btnPurClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPurClearActionPerformed
		txtPAccount.setText("");
		txtPTran.setText("");
		txtPDate.setText("");
		txtPConsole.setText("");
		txtPGames.setText("");
		txtPCont.setText("");
		txtPAcc.setText("");
		txtPMem.setText("");
	}//GEN-LAST:event_btnPurClearActionPerformed

	private void btnSaleClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaleClearActionPerformed
		txtSAccount.setText("");
		txtSEmpID.setText("");
		txtSTran.setText("");
		txtSDate.setText("");
		txtSConsole.setText("");
		txtSGames.setText("");
		txtSCont.setText("");
		txtSAcc.setText("");
		txtSMem.setText("");
	}//GEN-LAST:event_btnSaleClearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        frminvSearch.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int invsearchID = Integer.parseInt(txtinvSearch.getText());
        boolean invfound = false;
            
		for (Iterator<salesInvoice> iterator = sales.iterator(); iterator.hasNext();) {
			salesInvoice saleinsearch = iterator.next();
			if (saleinsearch.invoiceID == invsearchID){ 
				JOptionPane.showMessageDialog(this, saleinsearch.toString());
                invfound = true;
			}
		}
                
                for (Iterator<purchaseInvoice> iterator = purchases.iterator(); iterator.hasNext();) {
			purchaseInvoice purinsearch = iterator.next();
			if (purinsearch.invoiceID == invsearchID){ 
				JOptionPane.showMessageDialog(this, purinsearch.toString());
                invfound = true;
			}
		}
                
        if (invfound == false){
            JOptionPane.showMessageDialog(this, "Invoice Not Found.");
        }                
    }//GEN-LAST:event_jButton2ActionPerformed

	/**
	* @param args the command line arguments
	*/
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		* For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		*/
		
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Windows".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		}
		
		catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(project3MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		
		catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(project3MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} 

		catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(project3MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}

		catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(project3MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>


		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new project3MainGUI().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEmp;
    private javax.swing.JButton btnCAdd;
    private javax.swing.JButton btnInvenView;
    private javax.swing.JButton btnInvoiceView;
    private javax.swing.JButton btnMakePurch;
    private javax.swing.JButton btnMakeSale;
    private javax.swing.JButton btnModC;
    private javax.swing.JButton btnModEmp;
    private javax.swing.JButton btnPurClear;
    private javax.swing.JButton btnPurch;
    private javax.swing.JButton btnRCli;
    private javax.swing.JButton btnREmp;
    private javax.swing.JButton btnSale;
    private javax.swing.JButton btnSaleClear;
    private javax.swing.JButton btnUpgrade;
    private javax.swing.JButton btnclientAdd;
    private javax.swing.JButton btnclientMod;
    private javax.swing.JButton btnclientRemove;
    private javax.swing.JButton btnclientView;
    private javax.swing.JButton btnempAdd;
    private javax.swing.JButton btnempMod;
    private javax.swing.JButton btnempRem;
    private javax.swing.JButton btnempView;
    private javax.swing.JFrame frmCUp;
    private javax.swing.JFrame frmCliAdd;
    private javax.swing.JFrame frmCliMod;
    private javax.swing.JFrame frmCliRem;
    private javax.swing.JFrame frmCliView;
    private javax.swing.JFrame frmEmpAdd;
    private javax.swing.JFrame frmEmpMod;
    private javax.swing.JFrame frmEmpRem;
    private javax.swing.JFrame frmEmpView;
    private javax.swing.JFrame frmInv;
    private javax.swing.JFrame frmInvoiceView;
    private javax.swing.JFrame frmPurIn;
    private javax.swing.JFrame frmSaleIn;
    private javax.swing.JFrame frminvSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JScrollPane jpnlCliView;
    private javax.swing.JScrollPane jpnlEmpView;
    private javax.swing.JScrollPane jpnlPInvoice;
    private javax.swing.JScrollPane jpnlSCliView;
    private javax.swing.JScrollPane jpnlSInvoice;
    private javax.swing.JTextArea pnlCliView;
    private javax.swing.JTextArea pnlEmpView;
    private javax.swing.JTextPane pnlInv;
    private javax.swing.JTextPane pnlPInvoice;
    private javax.swing.JTextArea pnlSCliView;
    private javax.swing.JTextPane pnlSInvoice;
    private javax.swing.JTextField txtAEmpID;
    private javax.swing.JTextField txtAEmpName;
    private javax.swing.JTextField txtAEmpPhone;
    private javax.swing.JTextField txtAEmpWage;
    private javax.swing.JTextField txtCAccID;
    private javax.swing.JTextField txtCName;
    private javax.swing.JTextField txtCPhone;
    private javax.swing.JButton txtCUp;
    private javax.swing.JTextField txtCliUp;
    private javax.swing.JTextField txtMCAccID;
    private javax.swing.JTextField txtMCName;
    private javax.swing.JTextField txtMCPhone;
    private javax.swing.JTextField txtMCPoints;
    private javax.swing.JTextField txtMEmpID;
    private javax.swing.JTextField txtMEmpName;
    private javax.swing.JTextField txtMEmpPhone;
    private javax.swing.JTextField txtMEmpWage;
    private javax.swing.JTextField txtPAcc;
    private javax.swing.JTextField txtPAccount;
    private javax.swing.JTextField txtPConsole;
    private javax.swing.JTextField txtPCont;
    private javax.swing.JTextField txtPDate;
    private javax.swing.JTextField txtPGames;
    private javax.swing.JTextField txtPMem;
    private javax.swing.JTextField txtPPoints;
    private javax.swing.JTextField txtPTotal;
    private javax.swing.JTextField txtPTran;
    private javax.swing.JTextField txtRCliID;
    private javax.swing.JTextField txtREmpID;
    private javax.swing.JTextField txtSAcc;
    private javax.swing.JTextField txtSAccount;
    private javax.swing.JTextField txtSConsole;
    private javax.swing.JTextField txtSCont;
    private javax.swing.JTextField txtSDate;
    private javax.swing.JTextField txtSEmpID;
    private javax.swing.JTextField txtSGames;
    private javax.swing.JTextField txtSMem;
    private javax.swing.JTextField txtSPoints;
    private javax.swing.JTextField txtSTotal;
    private javax.swing.JTextField txtSTran;
    private javax.swing.JTextField txtinvSearch;
    // End of variables declaration//GEN-END:variables
}